# Generated by Django 4.2.7 on 2025-11-15 10:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('buyer_type', models.CharField(choices=[('developer', 'Developer/Construction Company'), ('company', 'Foreign Company (ISO Compliance)')], default='developer', max_length=20)),
                ('country', models.CharField(blank=True, help_text='For foreign companies', max_length=100)),
                ('iso_standards', models.JSONField(blank=True, default=list, help_text="ISO standards they need compliance for (e.g., ['ISO 14001', 'ISO 14064'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygon_coordinates', models.JSONField(help_text='GeoJSON polygon coordinates for the plantation boundary')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('species', models.CharField(default='Paulownia', max_length=100)),
                ('total_hectares', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('trees_per_hectare', models.PositiveIntegerField(default=1000, help_text='Number of trees per hectare (for sale calculation)')),
                ('price_per_tree', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per tree in USD', max_digits=10)),
                ('price_per_hectare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per hectare in USD', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plantation is available for sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50)),
                ('area_polygon', models.JSONField(help_text='GeoJSON polygon coordinates for this lot')),
                ('area_hectares', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('number_of_trees', models.PositiveIntegerField(help_text='Number of trees in this lot')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total price for this lot', max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_lots', to='core.plantation')),
            ],
            options={
                'ordering': ['lot_number'],
                'unique_together': {('plantation', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='TreePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of trees purchased')),
                ('price_per_tree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.buyer')),
                ('tree_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.treelot')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='NFTCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_token_id', models.CharField(blank=True, help_text='Blockchain NFT token ID (will be minted on Polygon)', max_length=255, null=True, unique=True)),
                ('blockchain_address', models.CharField(blank=True, help_text='Blockchain contract address', max_length=255)),
                ('transaction_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('co2_absorbed_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total CO₂ absorption for this certificate (kg)', max_digits=12)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nft_certificate', to='core.treepurchase')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ISOComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_standard', models.CharField(choices=[('ISO 14001', 'ISO 14001 - Environmental Management'), ('ISO 14064', 'ISO 14064 - Greenhouse Gas Accounting'), ('ISO 14067', 'ISO 14067 - Carbon Footprint'), ('ISO 50001', 'ISO 50001 - Energy Management')], max_length=50)),
                ('compliance_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_document_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_records', to='core.buyer')),
                ('nft_certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iso_records', to='core.nftcertificate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'nft_certificate', 'iso_standard')},
            },
        ),
        migrations.CreateModel(
            name='GrowthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_value', models.FloatField(blank=True, help_text='NDVI value (placeholder - replace with real satellite data)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('co2_absorbed_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CO₂ absorbed at this timestamp (kg)', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('plantation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_data', to='core.plantation')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plantation', '-timestamp'], name='core_growth_plantat_d03830_idx')],
            },
        ),
    ]
