# Generated by Django 4.2.7 on 2025-11-15 10:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, help_text='Home address (B2C)'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='company_logo',
            field=models.URLField(blank=True, help_text='URL to company logo image (stored in Google Cloud Storage)', null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (B2C)', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Company tax ID/VAT number', max_length=100),
        ),
        migrations.AddField(
            model_name='buyer',
            name='website',
            field=models.URLField(blank=True, help_text='Company website'),
        ),
        migrations.AddField(
            model_name='plantation',
            name='b2b_price_per_hectare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2B price per hectare in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='plantation',
            name='b2b_price_per_tree',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2B price per tree in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='plantation',
            name='b2c_price_per_hectare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2C price per hectare in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='plantation',
            name='b2c_price_per_tree',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2C price per tree in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='plantation',
            name='sector',
            field=models.CharField(choices=[('b2b', 'B2B - Business to Business'), ('b2c', 'B2C - Business to Consumer'), ('mixed', 'Mixed - Both B2B and B2C')], default='mixed', help_text='Sector type: B2B, B2C, or Mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='treelot',
            name='b2b_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2B price for this lot', max_digits=12),
        ),
        migrations.AddField(
            model_name='treelot',
            name='b2c_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='B2C price for this lot', max_digits=12),
        ),
        migrations.AddField(
            model_name='treelot',
            name='sector',
            field=models.CharField(choices=[('b2b', 'B2B - Business to Business'), ('b2c', 'B2C - Business to Consumer')], default='b2b', help_text='Sector this lot is assigned to (B2B or B2C)', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_type',
            field=models.CharField(choices=[('b2b', 'B2B - Business/Company'), ('b2c', 'B2C - Individual Consumer')], default='b2b', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Required for B2B', max_length=255),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(help_text='Contact person name (B2B) or full name (B2C)', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='price_per_hectare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price per hectare (deprecated - use b2b/b2c prices)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='plantation',
            name='price_per_tree',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price per tree (deprecated - use b2b/b2c prices)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='treelot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default price (deprecated - use b2b/b2c prices)', max_digits=12),
        ),
    ]
